server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lantu_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.lantu_web_java.entity
  configuration:
    map-underscore-to-camel-case: true
